gbf.wave = "0ssssccca...msMs"
gbf.analogue = [
    "0.5*VDDA", # first 4 's'
    "0.6*VDDA",
    "0.7*VDDA",
    "0.9*VDDA",
    "0.2*VDDA", # 3 'c'
    "0.8*VDDA",
    "0.3*VDDA",
    "[(t, (VDDA+VSSA)*(1 + sin(2*pi*t*3.5/Tmax))/2) for t in time]", # for 'a'
    "0.25*VDDA", # for last s
    "VDDA"
]