# testcase to demonstrate the possibility
# of overlaying several curves

mcu_clk.wave          = "P"
mcu_clk.repeat        = 10

# value of the 10-bits DAC of a SAR
dac.wave              = "c"
dac.repeat            = 10
dac.slewing           = 32
dac.vscale            = 4
dac.overlay           = true
dac.stroke            = [0, 0, 255, 255]
dac.stroke-dasharray  = [1, 3]
dac.fill              = [0, 0, 255, 255]
dac.font-size         = '9pt'
dac.order             = 2
dac.analogue          = [
  "VDDA*512/1024",
  "VDDA*256/1024",
  "VDDA*384/1024",
  "VDDA*320/1024",
  "VDDA*352/1024",
  "VDDA*336/1024",
  "VDDA*344/1024",
  "VDDA*340/1024",
  "VDDA*342/1024",
  "VDDA*341/1024"
]

# input  voltage to which compare
vin.wave              = "0a........"
vin.vscale            = 4
vin.overlay           = true
vin.stroke            = '#F00'
vin.stroke-dasharray  = [5, 3, 1, 5]
vin.stroke-width      = 1.5
vin.fill              = 'rgb(255, 0, 0)'
vin.font-size         = '0.4em'
vin.order             = 3
vin.analogue          = [
  "[(t, (VDDA/3)*(1-exp(-t/3))) for t in time]"
]

# vmax
vmax.wave             = "1........."
vmax.vscale           = 4
vmax.order            = 1
vmax.overlay          = true

# vmin
vmin.wave             = "l........."
vmin.vscale           = 4
vmin.order            = 4

dac_ref.wave              = "s"
dac_ref.repeat            = 10
dac_ref.slewing           = 32
dac_ref.vscale            = 4
dac_ref.stroke            = '#0000FFAA'
dac_ref.stroke-dasharray  = [1, 3]
dac_ref.fill              = '#0000FF'
dac_ref.order             = 2
dac_ref.analogue          = [
  "VDDA*512/1024",
  "VDDA*256/1024",
  "VDDA*384/1024",
  "VDDA*320/1024",
  "VDDA*352/1024",
  "VDDA*336/1024",
  "VDDA*344/1024",
  "VDDA*340/1024",
  "VDDA*342/1024",
  "VDDA*341/1024"
]
