# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.6.dev23+g96308a5.d20221223'
__version_tuple__ = version_tuple = (0, 0, 6, 'dev23', 'g96308a5.d20221223')
